// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa7f_NvKhQ-_d6p0QzO_-GTml4RRlTGaM',
    appId: '1:1024909651036:web:6f84e31dc9026389c80a99',
    messagingSenderId: '1024909651036',
    projectId: 'mynotes-flutter-project-racim',
    authDomain: 'mynotes-flutter-project-racim.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-racim.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ_0BQ_IpuPfM6WXQsKEQ3an3dlEpKFNY',
    appId: '1:1024909651036:android:c96e69441106fd41c80a99',
    messagingSenderId: '1024909651036',
    projectId: 'mynotes-flutter-project-racim',
    storageBucket: 'mynotes-flutter-project-racim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmfBB3usSBfNU7vLKMeEGwTjR_8c8fhpo',
    appId: '1:1024909651036:ios:414c92ce993a9132c80a99',
    messagingSenderId: '1024909651036',
    projectId: 'mynotes-flutter-project-racim',
    storageBucket: 'mynotes-flutter-project-racim.appspot.com',
    iosClientId: '1024909651036-opggi8s7j0dot6njc8dqtrld4tkbf0c7.apps.googleusercontent.com',
    iosBundleId: 'dz.SetupProjectCourse.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmfBB3usSBfNU7vLKMeEGwTjR_8c8fhpo',
    appId: '1:1024909651036:ios:414c92ce993a9132c80a99',
    messagingSenderId: '1024909651036',
    projectId: 'mynotes-flutter-project-racim',
    storageBucket: 'mynotes-flutter-project-racim.appspot.com',
    iosClientId: '1024909651036-opggi8s7j0dot6njc8dqtrld4tkbf0c7.apps.googleusercontent.com',
    iosBundleId: 'dz.SetupProjectCourse.mynotes',
  );
}
